remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: GFM
title: RevSharp
description: Open-Source C# Library for the Revolt chat platform.
show_downloads: false
